package info.tomacla.biketeam.common.amqp;

public enum FanoutBindings {

    PUBLICATION_PUBLISHED_MAIL(Exchanges.PUBLISH_PUBLICATION, Queues.PUBLICATION_PUBLISHED_MAIL),
    PUBLICATION_PUBLISHED_MATTERMOST(Exchanges.PUBLISH_PUBLICATION, Queues.PUBLICATION_PUBLISHED_MATTERMOST),
    RIDE_PUBLISHED_MAIL(Exchanges.PUBLISH_RIDE, Queues.RIDE_PUBLISHED_MAIL),
    RIDE_PUBLISHED_MATTERMOST(Exchanges.PUBLISH_RIDE, Queues.RIDE_PUBLISHED_MATTERMOST),
    RIDE_PUBLISHED_NOTIFICATION(Exchanges.PUBLISH_RIDE, Queues.RIDE_PUBLISHED_NOTIFICATION),
    TRIP_PUBLISHED_MAIL(Exchanges.PUBLISH_TRIP, Queues.TRIP_PUBLISHED_MAIL),
    TRIP_PUBLISHED_MATTERMOST(Exchanges.PUBLISH_TRIP, Queues.TRIP_PUBLISHED_MATTERMOST),
    TRIP_PUBLISHED_NOTIFICATION(Exchanges.PUBLISH_TRIP, Queues.TRIP_PUBLISHED_NOTIFICATION),
    RIDE_MESSAGE_PUBLISHED_NOTIFICATION(Exchanges.PUBLISH_RIDE_MESSAGE, Queues.RIDE_MESSAGE_PUBLISHED_NOTIFICATION),
    RIDE_MESSAGE_PUBLISHED_MATTERMOST(Exchanges.PUBLISH_RIDE_MESSAGE, Queues.RIDE_MESSAGE_PUBLISHED_MATTERMOST),
    TRIP_MESSAGE_PUBLISHED_NOTIFICATION(Exchanges.PUBLISH_TRIP_MESSAGE, Queues.TRIP_MESSAGE_PUBLISHED_NOTIFICATION),
    TRIP_MESSAGE_PUBLISHED_MATTERMOST(Exchanges.PUBLISH_TRIP_MESSAGE, Queues.TRIP_MESSAGE_PUBLISHED_MATTERMOST);

    final String exchange;
    final String queue;

    FanoutBindings(String exchange, String queue) {
        this.exchange = exchange;
        this.queue = queue;
    }

    public String getExchange() {
        return exchange;
    }

    public String getQueue() {
        return queue;
    }

}
