


    </div>

    <div class="mt-4 container-fluid">
        <div class="py-4 row justify-content-center bg-light border-top border-2">
            <div class="col-6 text-center">
                <img src="<@spring.url '/css/biketeam-logo.png' />" alt="Biketeam" width="100">
                <p class="small text-muted">©2021 Biketeam</p>
            </div>
        </div>
    </div>


</body>
</html>