


    </div>

    <#if !_embed>
        <div class="mt-4 container-fluid">
            <div class="py-4 row justify-content-center bg-light border-top border-2">
                <div class="col-6 text-center">
                    <p class="small text-muted"><a class="link-secondary" href="<@common.teamUrl '' '/legal-mentions' />">©2022 Biketeam</a><br/>Une création N-Peloton</p>
                </div>
            </div>
        </div>
    </#if>


</body>
</html>