<#include "_includes_head.ftlh">

<div class="row pt-2 justify-content-center">

    <#include "trip_nav.ftlh">

    <div class="row pt-2 justify-content-center">

        <aside class="col-12 col-md-3">

                <div class="markdown-content-toc mb-4"></div>

        </aside>

        <div class="col-12 col-md-9 pb-4">
                <div class="markdown-content"><#if notes??>${notes}</#if></div>
        </div>


    </div>


</div>

<#include "_includes_tail.ftlh">