name: develop_build_deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "target/biketeam.jar"
        target: "${{ secrets.JAR_PATH }}/latest"
    - name: Restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo /bin/systemctl stop ${{ secrets.SERVICE_NAME }}
          mv ${{ secrets.JAR_PATH }}/biketeam.jar ${{ secrets.JAR_PATH }}/biketeam_old.jar
          mv ${{ secrets.JAR_PATH }}/latest/target/biketeam.jar ${{ secrets.JAR_PATH }}/biketeam.jar
          sudo /bin/systemctl start ${{ secrets.SERVICE_NAME }}